POST http://localhost:3000/users
Content-Type: application/json
{
    "firstName": "Elliot",
    "lastName": "Alderson",
    "email": "ellioto@ald3erson.com",
    "password": "Password1*2"
}

POST http://localhost:3000/users/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE2LCJlbWFpbCI6ImJydWNleUB3YXluZS5jb20iLCJpYXQiOjE3NjM2NDk1NTgsImV4cCI6MTc2MzY1MzE1OCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.fjWpP6BFEeowtekSIM-04U6YZqYY7rTLJm3qn3U4aic
{
    "users" : [
        {
            "firstName": "Mark",
            "lastName": "Corrigan",
            "password": "Password1*",
            "email": "mark@corrigan.com"
        },
        {
            "firstName": "Bruce",
            "lastName": "Wayne",
            "password": "Password12*",
            "email": "brucey@wayne.com"
        }
    ]
}